### ISSUE TITLE
[docs] checklist

### ISSUE THREAD

**Issue by ASEM000** [ASEM000/serket#31]
- [ ] Toy model conversion from `PyTorch` 
- [ ] Toy model conversion from `keras` (i.e. show lazy approach)
- [x] orbax for checkpointing

**Comment by ASEM000** [comment]
Needs codediff doc util, like how flax does it.

![image](https://github.com/ASEM000/serket/assets/48389287/0a439031-858e-4fc6-90e6-97d64e39523e)
